title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sunJ0120.github.io/test_docs

aux_links:
  Template Repository: https://github.com/sunJ0120/test_docs

plugins:
  - jekyll-default-layout